deploy:
  environment: production
  stage: deploy
  tags:
    - windows
    - cmd
  only:
    - master
  script:
    - echo Deploy %HEROKU_APP_NAME%
    - dpl --provider=heroku --app=%HEROKU_APP_NAME% --api-key=%HEROKU_API_KEY%