deploy:
  stage: deploy
  tags:
    - windows
    - cmd
  only:
    - tags
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY # security add the heroku api to CI/CD setting