apiVersion: v1
kind: Namespace
metadata:
  name: db-touno-io
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-retain
provisioner: rancher.io/local-path
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-delete
provisioner: rancher.io/local-path
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-storage
spec:
  storageClassName: local-retain
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/mongo-4.4"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb
  namespace: db-touno-io
spec:
  storageClassName: local-retain
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    notice: mongodb
  name: mongodb
  namespace: db-touno-io
spec:
  selector:
    matchLabels:
      notice: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        notice: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.4
        imagePullPolicy: "Always"
        ports:
        - containerPort: 27017
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2"
        volumeMounts:
        - mountPath: /data/db
          name: db-storage
        livenessProbe:
          exec:
            command:
            - mongo
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 5
          timeoutSeconds: 3
          failureThreshold: 5
          periodSeconds: 2
          successThreshold: 1
      restartPolicy: Always
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: mongodb
---
apiVersion: v1
kind: Service
metadata:
  labels:
    notice: mongodb
  name: mongodb
  namespace: db-touno-io
spec:
  type: LoadBalancer
  ports:
  - name: "mongodb"
    port: 27017
    targetPort: 27017
  selector:
    notice: mongodb